var hierarchy =
[
    [ "_info", "struct__info.html", null ],
    [ "adxl345_t", "structadxl345__t.html", null ],
    [ "avr_gdb_t", "structavr__gdb__t.html", null ],
    [ "avr_gdb_watchpoints_t", "structavr__gdb__watchpoints__t.html", null ],
    [ "bitbang_i2c_t", "structbitbang__i2c__t.html", null ],
    [ "bitbang_spi_t", "structbitbang__spi__t.html", null ],
    [ "bitbang_uart_t", "structbitbang__uart__t.html", null ],
    [ "board", "classboard.html", [
      [ "bsim_gpsim", "classbsim__gpsim.html", [
        [ "cboard_gpboard", "classcboard__gpboard.html", null ]
      ] ],
      [ "bsim_picsim", "classbsim__picsim.html", [
        [ "cboard_Breadboard", "classcboard___breadboard.html", null ],
        [ "cboard_Curiosity", "classcboard___curiosity.html", null ],
        [ "cboard_Curiosity_HPC", "classcboard___curiosity___h_p_c.html", null ],
        [ "cboard_K16F", "classcboard___k16_f.html", null ],
        [ "cboard_McLab1", "classcboard___mc_lab1.html", null ],
        [ "cboard_McLab2", "classcboard___mc_lab2.html", null ],
        [ "cboard_PICGenios", "classcboard___p_i_c_genios.html", null ],
        [ "cboard_PQDB", "classcboard___p_q_d_b.html", null ],
        [ "cboard_Xpress", "classcboard___xpress.html", null ],
        [ "cboard_x", "classcboard__x.html", null ]
      ] ],
      [ "bsim_qemu", "classbsim__qemu.html", [
        [ "cboard_Blue_Pill", "classcboard___blue___pill.html", null ],
        [ "cboard_DevKitC", "classcboard___dev_kit_c.html", null ],
        [ "cboard_STM32_H103", "classcboard___s_t_m32___h103.html", null ]
      ] ],
      [ "bsim_remote", "classbsim__remote.html", [
        [ "cboard_RemoteTCP", "classcboard___remote_t_c_p.html", null ]
      ] ],
      [ "bsim_simavr", "classbsim__simavr.html", [
        [ "cboard_Arduino_Uno", "classcboard___arduino___uno.html", [
          [ "cboard_Arduino_Mega", "classcboard___arduino___mega.html", null ],
          [ "cboard_Arduino_Nano", "classcboard___arduino___nano.html", null ]
        ] ],
        [ "cboard_Breadboard", "classcboard___breadboard.html", null ],
        [ "cboard_Franzininho_DIY", "classcboard___franzininho___d_i_y.html", null ]
      ] ],
      [ "bsim_ucsim", "classbsim__ucsim.html", [
        [ "cboard_uCboard", "classcboard__u_cboard.html", null ]
      ] ]
    ] ],
    [ "board_desc", "structboard__desc.html", null ],
    [ "callbacks_t", "structcallbacks__t.html", null ],
    [ "ch_status_t", "structch__status__t.html", null ],
    [ "cmd_header_t", "structcmd__header__t.html", null ],
    [ "colorval_t", "structcolorval__t.html", null ],
    [ "COscilloscope", "class_c_oscilloscope.html", null ],
    [ "CPICSimLab", "class_c_p_i_c_sim_lab.html", null ],
    [ "CPWindow", null, [
      [ "CPWindow1", "class_c_p_window1.html", null ],
      [ "CPWindow2", "class_c_p_window2.html", null ],
      [ "CPWindow3", "class_c_p_window3.html", null ],
      [ "CPWindow4", "class_c_p_window4.html", null ],
      [ "CPWindow5", "class_c_p_window5.html", null ]
    ] ],
    [ "CSpareParts", "class_c_spare_parts.html", null ],
    [ "dhcp", "structdhcp.html", null ],
    [ "eth_w5500_t", "structeth__w5500__t.html", null ],
    [ "input_t", "structinput__t.html", null ],
    [ "io_74xx573_t", "structio__74xx573__t.html", null ],
    [ "io_74xx595_t", "structio__74xx595__t.html", null ],
    [ "io_MCP23X17_t", "structio___m_c_p23_x17__t.html", null ],
    [ "io_MM74C922_t", "structio___m_m74_c922__t.html", null ],
    [ "io_PCF8574_t", "structio___p_c_f8574__t.html", null ],
    [ "lcd_ili9341_t", "structlcd__ili9341__t.html", null ],
    [ "lcd_pcd8544_t", "structlcd__pcd8544__t.html", null ],
    [ "lcd_pcf8833_t", "structlcd__pcf8833__t.html", null ],
    [ "lcd_ssd1306_t", "structlcd__ssd1306__t.html", null ],
    [ "lcd_t", "structlcd__t.html", null ],
    [ "ldd_max72xx_t", "structldd__max72xx__t.html", null ],
    [ "led_ws2812b_t", "structled__ws2812b__t.html", null ],
    [ "mi2c_t", "structmi2c__t.html", null ],
    [ "mpu6050_t", "structmpu6050__t.html", null ],
    [ "output_t", "structoutput__t.html", null ],
    [ "part", "classpart.html", [
      [ "cpart_7s_display", "classcpart__7s__display.html", null ],
      [ "cpart_7s_display_dec", "classcpart__7s__display__dec.html", null ],
      [ "cpart_ADXL345", "classcpart___a_d_x_l345.html", null ],
      [ "cpart_Buzzer", "classcpart___buzzer.html", null ],
      [ "cpart_CPU_DBG", "classcpart___c_p_u___d_b_g.html", null ],
      [ "cpart_ETH_w5500", "classcpart___e_t_h__w5500.html", null ],
      [ "cpart_IO_74xx573", "classcpart___i_o__74xx573.html", null ],
      [ "cpart_IO_74xx595", "classcpart___i_o__74xx595.html", null ],
      [ "cpart_IO_MCP23S17", "classcpart___i_o___m_c_p23_s17.html", null ],
      [ "cpart_IO_MM74C922", "classcpart___i_o___m_m74_c922.html", null ],
      [ "cpart_IO_PCF8574", "classcpart___i_o___p_c_f8574.html", null ],
      [ "cpart_Jumpers", "classcpart___jumpers.html", null ],
      [ "cpart_LCD_hd44780", "classcpart___l_c_d__hd44780.html", null ],
      [ "cpart_LCD_ili9341", "classcpart___l_c_d__ili9341.html", null ],
      [ "cpart_LCD_pcd8544", "classcpart___l_c_d__pcd8544.html", null ],
      [ "cpart_LCD_pcf8833", "classcpart___l_c_d__pcf8833.html", null ],
      [ "cpart_LCD_ssd1306", "classcpart___l_c_d__ssd1306.html", null ],
      [ "cpart_LDR", "classcpart___l_d_r.html", null ],
      [ "cpart_MI2C_24CXXX", "classcpart___m_i2_c__24_c_x_x_x.html", null ],
      [ "cpart_MPU6050", "classcpart___m_p_u6050.html", null ],
      [ "cpart_RTC_ds1307", "classcpart___r_t_c__ds1307.html", null ],
      [ "cpart_RTC_pfc8563", "classcpart___r_t_c__pfc8563.html", null ],
      [ "cpart_SDCard", "classcpart___s_d_card.html", null ],
      [ "cpart_SignalGenerator", "classcpart___signal_generator.html", null ],
      [ "cpart_TEXT", "classcpart___t_e_x_t.html", null ],
      [ "cpart_UART", "classcpart___u_a_r_t.html", null ],
      [ "cpart_VCD_Dump", "classcpart___v_c_d___dump.html", null ],
      [ "cpart_VCD_Dump_DBG", "classcpart___v_c_d___dump___d_b_g.html", null ],
      [ "cpart_VCD_Dump_an", "classcpart___v_c_d___dump__an.html", null ],
      [ "cpart_VCD_Play", "classcpart___v_c_d___play.html", null ],
      [ "cpart_bmp180", "classcpart__bmp180.html", null ],
      [ "cpart_bmp280", "classcpart__bmp280.html", null ],
      [ "cpart_dcmotor", "classcpart__dcmotor.html", null ],
      [ "cpart_dht11", "classcpart__dht11.html", null ],
      [ "cpart_dht22", "classcpart__dht22.html", null ],
      [ "cpart_ds1621", "classcpart__ds1621.html", null ],
      [ "cpart_ds18b20", "classcpart__ds18b20.html", null ],
      [ "cpart_dtfunc", "classcpart__dtfunc.html", null ],
      [ "cpart_encoder", "classcpart__encoder.html", null ],
      [ "cpart_fixedv", "classcpart__fixedv.html", null ],
      [ "cpart_fm50", "classcpart__fm50.html", null ],
      [ "cpart_gamepad", "classcpart__gamepad.html", null ],
      [ "cpart_gamepad_an", "classcpart__gamepad__an.html", null ],
      [ "cpart_hcsr04", "classcpart__hcsr04.html", null ],
      [ "cpart_keypad", "classcpart__keypad.html", null ],
      [ "cpart_led_matrix", "classcpart__led__matrix.html", null ],
      [ "cpart_led_ws2812b", "classcpart__led__ws2812b.html", null ],
      [ "cpart_leds", "classcpart__leds.html", null ],
      [ "cpart_lm35", "classcpart__lm35.html", null ],
      [ "cpart_pbuttons", "classcpart__pbuttons.html", null ],
      [ "cpart_pbuttons_an", "classcpart__pbuttons__an.html", null ],
      [ "cpart_pot", "classcpart__pot.html", null ],
      [ "cpart_pot_r", "classcpart__pot__r.html", null ],
      [ "cpart_rgb_led", "classcpart__rgb__led.html", null ],
      [ "cpart_servo", "classcpart__servo.html", null ],
      [ "cpart_sht3x", "classcpart__sht3x.html", null ],
      [ "cpart_step", "classcpart__step.html", null ],
      [ "cpart_switches", "classcpart__switches.html", null ],
      [ "cpart_tempsys", "classcpart__tempsys.html", null ],
      [ "cpart_vterm", "classcpart__vterm.html", null ]
    ] ],
    [ "part_desc", "structpart__desc.html", null ],
    [ "PCWProp", "struct_p_c_w_prop.html", null ],
    [ "QEMUTimer", "struct_q_e_m_u_timer.html", null ],
    [ "rgb_color", "structrgb__color.html", null ],
    [ "rtc_ds1307_t", "structrtc__ds1307__t.html", null ],
    [ "rtc_pfc8563_t", "structrtc__pfc8563__t.html", null ],
    [ "sdcard_t", "structsdcard__t.html", null ],
    [ "sen_bmp180_t", "structsen__bmp180__t.html", null ],
    [ "sen_bmp280_t", "structsen__bmp280__t.html", null ],
    [ "sen_dhtxx_t", "structsen__dhtxx__t.html", null ],
    [ "sen_ds1621_t", "structsen__ds1621__t.html", null ],
    [ "sen_ds18b20_t", "structsen__ds18b20__t.html", null ],
    [ "SWBounce_t", "struct_s_w_bounce__t.html", null ],
    [ "Timers_t", "struct_timers__t.html", null ],
    [ "tsc_XPT2046_t", "structtsc___x_p_t2046__t.html", null ],
    [ "uart_t", "structuart__t.html", null ],
    [ "user_timer_t", "structuser__timer__t.html", null ],
    [ "usi_t", "structusi__t.html", null ],
    [ "vcd_reg_t", "structvcd__reg__t.html", null ],
    [ "vterm_t", "structvterm__t.html", null ]
];